package edu.ynu.software.Rocket.excellentHouse.entity;

import java.util.Date;

public class CollectionDesigner {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_designer.id
     *
     * @mbggenerated Thu Sep 07 08:40:02 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_designer.designer_id
     *
     * @mbggenerated Thu Sep 07 08:40:02 CST 2017
     */
    private Integer designerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_designer.user_id
     *
     * @mbggenerated Thu Sep 07 08:40:02 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_designer.create_time
     *
     * @mbggenerated Thu Sep 07 08:40:02 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_designer.is_vaild
     *
     * @mbggenerated Thu Sep 07 08:40:02 CST 2017
     */
    private Boolean isVaild;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_designer
     *
     * @mbggenerated Thu Sep 07 08:40:02 CST 2017
     */
    public CollectionDesigner(Integer id, Integer designerId, Integer userId, Date createTime, Boolean isVaild) {
        this.id = id;
        this.designerId = designerId;
        this.userId = userId;
        this.createTime = createTime;
        this.isVaild = isVaild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_designer
     *
     * @mbggenerated Thu Sep 07 08:40:02 CST 2017
     */
    public CollectionDesigner() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_designer.id
     *
     * @return the value of collection_designer.id
     *
     * @mbggenerated Thu Sep 07 08:40:02 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_designer.id
     *
     * @param id the value for collection_designer.id
     *
     * @mbggenerated Thu Sep 07 08:40:02 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_designer.designer_id
     *
     * @return the value of collection_designer.designer_id
     *
     * @mbggenerated Thu Sep 07 08:40:02 CST 2017
     */
    public Integer getDesignerId() {
        return designerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_designer.designer_id
     *
     * @param designerId the value for collection_designer.designer_id
     *
     * @mbggenerated Thu Sep 07 08:40:02 CST 2017
     */
    public void setDesignerId(Integer designerId) {
        this.designerId = designerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_designer.user_id
     *
     * @return the value of collection_designer.user_id
     *
     * @mbggenerated Thu Sep 07 08:40:02 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_designer.user_id
     *
     * @param userId the value for collection_designer.user_id
     *
     * @mbggenerated Thu Sep 07 08:40:02 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_designer.create_time
     *
     * @return the value of collection_designer.create_time
     *
     * @mbggenerated Thu Sep 07 08:40:02 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_designer.create_time
     *
     * @param createTime the value for collection_designer.create_time
     *
     * @mbggenerated Thu Sep 07 08:40:02 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_designer.is_vaild
     *
     * @return the value of collection_designer.is_vaild
     *
     * @mbggenerated Thu Sep 07 08:40:02 CST 2017
     */
    public Boolean getIsVaild() {
        return isVaild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_designer.is_vaild
     *
     * @param isVaild the value for collection_designer.is_vaild
     *
     * @mbggenerated Thu Sep 07 08:40:02 CST 2017
     */
    public void setIsVaild(Boolean isVaild) {
        this.isVaild = isVaild;
    }
}