package edu.ynu.software.Rocket.excellentHouse.entity;

public class Company {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.id
     *
     * @mbggenerated Thu Sep 07 08:40:22 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.name
     *
     * @mbggenerated Thu Sep 07 08:40:22 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.info
     *
     * @mbggenerated Thu Sep 07 08:40:22 CST 2017
     */
    private String info;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.address
     *
     * @mbggenerated Thu Sep 07 08:40:22 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.create_time
     *
     * @mbggenerated Thu Sep 07 08:40:22 CST 2017
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.is_vaild
     *
     * @mbggenerated Thu Sep 07 08:40:22 CST 2017
     */
    private Boolean isVaild;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbggenerated Thu Sep 07 08:40:22 CST 2017
     */
    public Company(Integer id, String name, String info, String address, String createTime, Boolean isVaild) {
        this.id = id;
        this.name = name;
        this.info = info;
        this.address = address;
        this.createTime = createTime;
        this.isVaild = isVaild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbggenerated Thu Sep 07 08:40:22 CST 2017
     */
    public Company() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.id
     *
     * @return the value of company.id
     *
     * @mbggenerated Thu Sep 07 08:40:22 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.id
     *
     * @param id the value for company.id
     *
     * @mbggenerated Thu Sep 07 08:40:22 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.name
     *
     * @return the value of company.name
     *
     * @mbggenerated Thu Sep 07 08:40:22 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.name
     *
     * @param name the value for company.name
     *
     * @mbggenerated Thu Sep 07 08:40:22 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.info
     *
     * @return the value of company.info
     *
     * @mbggenerated Thu Sep 07 08:40:22 CST 2017
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.info
     *
     * @param info the value for company.info
     *
     * @mbggenerated Thu Sep 07 08:40:22 CST 2017
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.address
     *
     * @return the value of company.address
     *
     * @mbggenerated Thu Sep 07 08:40:22 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.address
     *
     * @param address the value for company.address
     *
     * @mbggenerated Thu Sep 07 08:40:22 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.create_time
     *
     * @return the value of company.create_time
     *
     * @mbggenerated Thu Sep 07 08:40:22 CST 2017
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.create_time
     *
     * @param createTime the value for company.create_time
     *
     * @mbggenerated Thu Sep 07 08:40:22 CST 2017
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.is_vaild
     *
     * @return the value of company.is_vaild
     *
     * @mbggenerated Thu Sep 07 08:40:22 CST 2017
     */
    public Boolean getIsVaild() {
        return isVaild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.is_vaild
     *
     * @param isVaild the value for company.is_vaild
     *
     * @mbggenerated Thu Sep 07 08:40:22 CST 2017
     */
    public void setIsVaild(Boolean isVaild) {
        this.isVaild = isVaild;
    }
}