package edu.ynu.software.Rocket.excellentHouse.entity;

import java.util.Date;

public class Designer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column designer.id
     *
     * @mbggenerated Thu Sep 07 08:40:39 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column designer.deco_company_id
     *
     * @mbggenerated Thu Sep 07 08:40:39 CST 2017
     */
    private Integer decoCompanyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column designer.name
     *
     * @mbggenerated Thu Sep 07 08:40:39 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column designer.well_in_style
     *
     * @mbggenerated Thu Sep 07 08:40:39 CST 2017
     */
    private String wellInStyle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column designer.phone
     *
     * @mbggenerated Thu Sep 07 08:40:39 CST 2017
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column designer.create_time
     *
     * @mbggenerated Thu Sep 07 08:40:39 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column designer.is_vaild
     *
     * @mbggenerated Thu Sep 07 08:40:39 CST 2017
     */
    private Boolean isVaild;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table designer
     *
     * @mbggenerated Thu Sep 07 08:40:39 CST 2017
     */
    public Designer(Integer id, Integer decoCompanyId, String name, String wellInStyle, String phone, Date createTime, Boolean isVaild) {
        this.id = id;
        this.decoCompanyId = decoCompanyId;
        this.name = name;
        this.wellInStyle = wellInStyle;
        this.phone = phone;
        this.createTime = createTime;
        this.isVaild = isVaild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table designer
     *
     * @mbggenerated Thu Sep 07 08:40:39 CST 2017
     */
    public Designer() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column designer.id
     *
     * @return the value of designer.id
     *
     * @mbggenerated Thu Sep 07 08:40:39 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column designer.id
     *
     * @param id the value for designer.id
     *
     * @mbggenerated Thu Sep 07 08:40:39 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column designer.deco_company_id
     *
     * @return the value of designer.deco_company_id
     *
     * @mbggenerated Thu Sep 07 08:40:39 CST 2017
     */
    public Integer getDecoCompanyId() {
        return decoCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column designer.deco_company_id
     *
     * @param decoCompanyId the value for designer.deco_company_id
     *
     * @mbggenerated Thu Sep 07 08:40:39 CST 2017
     */
    public void setDecoCompanyId(Integer decoCompanyId) {
        this.decoCompanyId = decoCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column designer.name
     *
     * @return the value of designer.name
     *
     * @mbggenerated Thu Sep 07 08:40:39 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column designer.name
     *
     * @param name the value for designer.name
     *
     * @mbggenerated Thu Sep 07 08:40:39 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column designer.well_in_style
     *
     * @return the value of designer.well_in_style
     *
     * @mbggenerated Thu Sep 07 08:40:39 CST 2017
     */
    public String getWellInStyle() {
        return wellInStyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column designer.well_in_style
     *
     * @param wellInStyle the value for designer.well_in_style
     *
     * @mbggenerated Thu Sep 07 08:40:39 CST 2017
     */
    public void setWellInStyle(String wellInStyle) {
        this.wellInStyle = wellInStyle == null ? null : wellInStyle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column designer.phone
     *
     * @return the value of designer.phone
     *
     * @mbggenerated Thu Sep 07 08:40:39 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column designer.phone
     *
     * @param phone the value for designer.phone
     *
     * @mbggenerated Thu Sep 07 08:40:39 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column designer.create_time
     *
     * @return the value of designer.create_time
     *
     * @mbggenerated Thu Sep 07 08:40:39 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column designer.create_time
     *
     * @param createTime the value for designer.create_time
     *
     * @mbggenerated Thu Sep 07 08:40:39 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column designer.is_vaild
     *
     * @return the value of designer.is_vaild
     *
     * @mbggenerated Thu Sep 07 08:40:39 CST 2017
     */
    public Boolean getIsVaild() {
        return isVaild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column designer.is_vaild
     *
     * @param isVaild the value for designer.is_vaild
     *
     * @mbggenerated Thu Sep 07 08:40:39 CST 2017
     */
    public void setIsVaild(Boolean isVaild) {
        this.isVaild = isVaild;
    }
}