package edu.ynu.software.Rocket.excellentHouse.entity;

import java.math.BigDecimal;
import java.util.Date;

public class HouseType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_type.id
     *
     * @mbggenerated Thu Sep 07 08:40:49 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_type.premises_id
     *
     * @mbggenerated Thu Sep 07 08:40:49 CST 2017
     */
    private Integer premisesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_type.name
     *
     * @mbggenerated Thu Sep 07 08:40:49 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_type.area
     *
     * @mbggenerated Thu Sep 07 08:40:49 CST 2017
     */
    private Integer area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_type.avePrice
     *
     * @mbggenerated Thu Sep 07 08:40:49 CST 2017
     */
    private BigDecimal aveprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_type.totalPrice
     *
     * @mbggenerated Thu Sep 07 08:40:49 CST 2017
     */
    private BigDecimal totalprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_type.bedroomNum
     *
     * @mbggenerated Thu Sep 07 08:40:49 CST 2017
     */
    private Integer bedroomnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_type.hallNum
     *
     * @mbggenerated Thu Sep 07 08:40:49 CST 2017
     */
    private Integer hallnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_type.bathroomNum
     *
     * @mbggenerated Thu Sep 07 08:40:49 CST 2017
     */
    private Integer bathroomnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_type.kitchenNum
     *
     * @mbggenerated Thu Sep 07 08:40:49 CST 2017
     */
    private Integer kitchennum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_type.introduction
     *
     * @mbggenerated Thu Sep 07 08:40:49 CST 2017
     */
    private String introduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_type.create_time
     *
     * @mbggenerated Thu Sep 07 08:40:49 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_type.is_vaild
     *
     * @mbggenerated Thu Sep 07 08:40:49 CST 2017
     */
    private Boolean isVaild;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_type
     *
     * @mbggenerated Thu Sep 07 08:40:49 CST 2017
     */
    public HouseType(Integer id, Integer premisesId, String name, Integer area, BigDecimal aveprice, BigDecimal totalprice, Integer bedroomnum, Integer hallnum, Integer bathroomnum, Integer kitchennum, String introduction, Date createTime, Boolean isVaild) {
        this.id = id;
        this.premisesId = premisesId;
        this.name = name;
        this.area = area;
        this.aveprice = aveprice;
        this.totalprice = totalprice;
        this.bedroomnum = bedroomnum;
        this.hallnum = hallnum;
        this.bathroomnum = bathroomnum;
        this.kitchennum = kitchennum;
        this.introduction = introduction;
        this.createTime = createTime;
        this.isVaild = isVaild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_type
     *
     * @mbggenerated Thu Sep 07 08:40:49 CST 2017
     */
    public HouseType() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_type.id
     *
     * @return the value of house_type.id
     *
     * @mbggenerated Thu Sep 07 08:40:49 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_type.id
     *
     * @param id the value for house_type.id
     *
     * @mbggenerated Thu Sep 07 08:40:49 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_type.premises_id
     *
     * @return the value of house_type.premises_id
     *
     * @mbggenerated Thu Sep 07 08:40:49 CST 2017
     */
    public Integer getPremisesId() {
        return premisesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_type.premises_id
     *
     * @param premisesId the value for house_type.premises_id
     *
     * @mbggenerated Thu Sep 07 08:40:49 CST 2017
     */
    public void setPremisesId(Integer premisesId) {
        this.premisesId = premisesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_type.name
     *
     * @return the value of house_type.name
     *
     * @mbggenerated Thu Sep 07 08:40:49 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_type.name
     *
     * @param name the value for house_type.name
     *
     * @mbggenerated Thu Sep 07 08:40:49 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_type.area
     *
     * @return the value of house_type.area
     *
     * @mbggenerated Thu Sep 07 08:40:49 CST 2017
     */
    public Integer getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_type.area
     *
     * @param area the value for house_type.area
     *
     * @mbggenerated Thu Sep 07 08:40:49 CST 2017
     */
    public void setArea(Integer area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_type.avePrice
     *
     * @return the value of house_type.avePrice
     *
     * @mbggenerated Thu Sep 07 08:40:49 CST 2017
     */
    public BigDecimal getAveprice() {
        return aveprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_type.avePrice
     *
     * @param aveprice the value for house_type.avePrice
     *
     * @mbggenerated Thu Sep 07 08:40:49 CST 2017
     */
    public void setAveprice(BigDecimal aveprice) {
        this.aveprice = aveprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_type.totalPrice
     *
     * @return the value of house_type.totalPrice
     *
     * @mbggenerated Thu Sep 07 08:40:49 CST 2017
     */
    public BigDecimal getTotalprice() {
        return totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_type.totalPrice
     *
     * @param totalprice the value for house_type.totalPrice
     *
     * @mbggenerated Thu Sep 07 08:40:49 CST 2017
     */
    public void setTotalprice(BigDecimal totalprice) {
        this.totalprice = totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_type.bedroomNum
     *
     * @return the value of house_type.bedroomNum
     *
     * @mbggenerated Thu Sep 07 08:40:49 CST 2017
     */
    public Integer getBedroomnum() {
        return bedroomnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_type.bedroomNum
     *
     * @param bedroomnum the value for house_type.bedroomNum
     *
     * @mbggenerated Thu Sep 07 08:40:49 CST 2017
     */
    public void setBedroomnum(Integer bedroomnum) {
        this.bedroomnum = bedroomnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_type.hallNum
     *
     * @return the value of house_type.hallNum
     *
     * @mbggenerated Thu Sep 07 08:40:49 CST 2017
     */
    public Integer getHallnum() {
        return hallnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_type.hallNum
     *
     * @param hallnum the value for house_type.hallNum
     *
     * @mbggenerated Thu Sep 07 08:40:49 CST 2017
     */
    public void setHallnum(Integer hallnum) {
        this.hallnum = hallnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_type.bathroomNum
     *
     * @return the value of house_type.bathroomNum
     *
     * @mbggenerated Thu Sep 07 08:40:49 CST 2017
     */
    public Integer getBathroomnum() {
        return bathroomnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_type.bathroomNum
     *
     * @param bathroomnum the value for house_type.bathroomNum
     *
     * @mbggenerated Thu Sep 07 08:40:49 CST 2017
     */
    public void setBathroomnum(Integer bathroomnum) {
        this.bathroomnum = bathroomnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_type.kitchenNum
     *
     * @return the value of house_type.kitchenNum
     *
     * @mbggenerated Thu Sep 07 08:40:49 CST 2017
     */
    public Integer getKitchennum() {
        return kitchennum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_type.kitchenNum
     *
     * @param kitchennum the value for house_type.kitchenNum
     *
     * @mbggenerated Thu Sep 07 08:40:49 CST 2017
     */
    public void setKitchennum(Integer kitchennum) {
        this.kitchennum = kitchennum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_type.introduction
     *
     * @return the value of house_type.introduction
     *
     * @mbggenerated Thu Sep 07 08:40:49 CST 2017
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_type.introduction
     *
     * @param introduction the value for house_type.introduction
     *
     * @mbggenerated Thu Sep 07 08:40:49 CST 2017
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_type.create_time
     *
     * @return the value of house_type.create_time
     *
     * @mbggenerated Thu Sep 07 08:40:49 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_type.create_time
     *
     * @param createTime the value for house_type.create_time
     *
     * @mbggenerated Thu Sep 07 08:40:49 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_type.is_vaild
     *
     * @return the value of house_type.is_vaild
     *
     * @mbggenerated Thu Sep 07 08:40:49 CST 2017
     */
    public Boolean getIsVaild() {
        return isVaild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_type.is_vaild
     *
     * @param isVaild the value for house_type.is_vaild
     *
     * @mbggenerated Thu Sep 07 08:40:49 CST 2017
     */
    public void setIsVaild(Boolean isVaild) {
        this.isVaild = isVaild;
    }
}