package edu.ynu.software.Rocket.excellentHouse.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class HouseTypeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table house_type
     *
     * @mbggenerated Fri Sep 15 09:37:31 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table house_type
     *
     * @mbggenerated Fri Sep 15 09:37:31 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table house_type
     *
     * @mbggenerated Fri Sep 15 09:37:31 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_type
     *
     * @mbggenerated Fri Sep 15 09:37:31 CST 2017
     */
    public HouseTypeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_type
     *
     * @mbggenerated Fri Sep 15 09:37:31 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_type
     *
     * @mbggenerated Fri Sep 15 09:37:31 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_type
     *
     * @mbggenerated Fri Sep 15 09:37:31 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_type
     *
     * @mbggenerated Fri Sep 15 09:37:31 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_type
     *
     * @mbggenerated Fri Sep 15 09:37:31 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_type
     *
     * @mbggenerated Fri Sep 15 09:37:31 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_type
     *
     * @mbggenerated Fri Sep 15 09:37:31 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_type
     *
     * @mbggenerated Fri Sep 15 09:37:31 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_type
     *
     * @mbggenerated Fri Sep 15 09:37:31 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_type
     *
     * @mbggenerated Fri Sep 15 09:37:31 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table house_type
     *
     * @mbggenerated Fri Sep 15 09:37:31 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPremisesIdIsNull() {
            addCriterion("premises_id is null");
            return (Criteria) this;
        }

        public Criteria andPremisesIdIsNotNull() {
            addCriterion("premises_id is not null");
            return (Criteria) this;
        }

        public Criteria andPremisesIdEqualTo(Integer value) {
            addCriterion("premises_id =", value, "premisesId");
            return (Criteria) this;
        }

        public Criteria andPremisesIdNotEqualTo(Integer value) {
            addCriterion("premises_id <>", value, "premisesId");
            return (Criteria) this;
        }

        public Criteria andPremisesIdGreaterThan(Integer value) {
            addCriterion("premises_id >", value, "premisesId");
            return (Criteria) this;
        }

        public Criteria andPremisesIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("premises_id >=", value, "premisesId");
            return (Criteria) this;
        }

        public Criteria andPremisesIdLessThan(Integer value) {
            addCriterion("premises_id <", value, "premisesId");
            return (Criteria) this;
        }

        public Criteria andPremisesIdLessThanOrEqualTo(Integer value) {
            addCriterion("premises_id <=", value, "premisesId");
            return (Criteria) this;
        }

        public Criteria andPremisesIdIn(List<Integer> values) {
            addCriterion("premises_id in", values, "premisesId");
            return (Criteria) this;
        }

        public Criteria andPremisesIdNotIn(List<Integer> values) {
            addCriterion("premises_id not in", values, "premisesId");
            return (Criteria) this;
        }

        public Criteria andPremisesIdBetween(Integer value1, Integer value2) {
            addCriterion("premises_id between", value1, value2, "premisesId");
            return (Criteria) this;
        }

        public Criteria andPremisesIdNotBetween(Integer value1, Integer value2) {
            addCriterion("premises_id not between", value1, value2, "premisesId");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andAreaIsNull() {
            addCriterion("area is null");
            return (Criteria) this;
        }

        public Criteria andAreaIsNotNull() {
            addCriterion("area is not null");
            return (Criteria) this;
        }

        public Criteria andAreaEqualTo(Integer value) {
            addCriterion("area =", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotEqualTo(Integer value) {
            addCriterion("area <>", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaGreaterThan(Integer value) {
            addCriterion("area >", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaGreaterThanOrEqualTo(Integer value) {
            addCriterion("area >=", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLessThan(Integer value) {
            addCriterion("area <", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLessThanOrEqualTo(Integer value) {
            addCriterion("area <=", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaIn(List<Integer> values) {
            addCriterion("area in", values, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotIn(List<Integer> values) {
            addCriterion("area not in", values, "area");
            return (Criteria) this;
        }

        public Criteria andAreaBetween(Integer value1, Integer value2) {
            addCriterion("area between", value1, value2, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotBetween(Integer value1, Integer value2) {
            addCriterion("area not between", value1, value2, "area");
            return (Criteria) this;
        }

        public Criteria andAvePriceIsNull() {
            addCriterion("ave_price is null");
            return (Criteria) this;
        }

        public Criteria andAvePriceIsNotNull() {
            addCriterion("ave_price is not null");
            return (Criteria) this;
        }

        public Criteria andAvePriceEqualTo(BigDecimal value) {
            addCriterion("ave_price =", value, "avePrice");
            return (Criteria) this;
        }

        public Criteria andAvePriceNotEqualTo(BigDecimal value) {
            addCriterion("ave_price <>", value, "avePrice");
            return (Criteria) this;
        }

        public Criteria andAvePriceGreaterThan(BigDecimal value) {
            addCriterion("ave_price >", value, "avePrice");
            return (Criteria) this;
        }

        public Criteria andAvePriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ave_price >=", value, "avePrice");
            return (Criteria) this;
        }

        public Criteria andAvePriceLessThan(BigDecimal value) {
            addCriterion("ave_price <", value, "avePrice");
            return (Criteria) this;
        }

        public Criteria andAvePriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ave_price <=", value, "avePrice");
            return (Criteria) this;
        }

        public Criteria andAvePriceIn(List<BigDecimal> values) {
            addCriterion("ave_price in", values, "avePrice");
            return (Criteria) this;
        }

        public Criteria andAvePriceNotIn(List<BigDecimal> values) {
            addCriterion("ave_price not in", values, "avePrice");
            return (Criteria) this;
        }

        public Criteria andAvePriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ave_price between", value1, value2, "avePrice");
            return (Criteria) this;
        }

        public Criteria andAvePriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ave_price not between", value1, value2, "avePrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceIsNull() {
            addCriterion("total_price is null");
            return (Criteria) this;
        }

        public Criteria andTotalPriceIsNotNull() {
            addCriterion("total_price is not null");
            return (Criteria) this;
        }

        public Criteria andTotalPriceEqualTo(BigDecimal value) {
            addCriterion("total_price =", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceNotEqualTo(BigDecimal value) {
            addCriterion("total_price <>", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceGreaterThan(BigDecimal value) {
            addCriterion("total_price >", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("total_price >=", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceLessThan(BigDecimal value) {
            addCriterion("total_price <", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("total_price <=", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceIn(List<BigDecimal> values) {
            addCriterion("total_price in", values, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceNotIn(List<BigDecimal> values) {
            addCriterion("total_price not in", values, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("total_price between", value1, value2, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("total_price not between", value1, value2, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andBedroomNumIsNull() {
            addCriterion("bedroom_num is null");
            return (Criteria) this;
        }

        public Criteria andBedroomNumIsNotNull() {
            addCriterion("bedroom_num is not null");
            return (Criteria) this;
        }

        public Criteria andBedroomNumEqualTo(Integer value) {
            addCriterion("bedroom_num =", value, "bedroomNum");
            return (Criteria) this;
        }

        public Criteria andBedroomNumNotEqualTo(Integer value) {
            addCriterion("bedroom_num <>", value, "bedroomNum");
            return (Criteria) this;
        }

        public Criteria andBedroomNumGreaterThan(Integer value) {
            addCriterion("bedroom_num >", value, "bedroomNum");
            return (Criteria) this;
        }

        public Criteria andBedroomNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("bedroom_num >=", value, "bedroomNum");
            return (Criteria) this;
        }

        public Criteria andBedroomNumLessThan(Integer value) {
            addCriterion("bedroom_num <", value, "bedroomNum");
            return (Criteria) this;
        }

        public Criteria andBedroomNumLessThanOrEqualTo(Integer value) {
            addCriterion("bedroom_num <=", value, "bedroomNum");
            return (Criteria) this;
        }

        public Criteria andBedroomNumIn(List<Integer> values) {
            addCriterion("bedroom_num in", values, "bedroomNum");
            return (Criteria) this;
        }

        public Criteria andBedroomNumNotIn(List<Integer> values) {
            addCriterion("bedroom_num not in", values, "bedroomNum");
            return (Criteria) this;
        }

        public Criteria andBedroomNumBetween(Integer value1, Integer value2) {
            addCriterion("bedroom_num between", value1, value2, "bedroomNum");
            return (Criteria) this;
        }

        public Criteria andBedroomNumNotBetween(Integer value1, Integer value2) {
            addCriterion("bedroom_num not between", value1, value2, "bedroomNum");
            return (Criteria) this;
        }

        public Criteria andHallNumIsNull() {
            addCriterion("hall_num is null");
            return (Criteria) this;
        }

        public Criteria andHallNumIsNotNull() {
            addCriterion("hall_num is not null");
            return (Criteria) this;
        }

        public Criteria andHallNumEqualTo(Integer value) {
            addCriterion("hall_num =", value, "hallNum");
            return (Criteria) this;
        }

        public Criteria andHallNumNotEqualTo(Integer value) {
            addCriterion("hall_num <>", value, "hallNum");
            return (Criteria) this;
        }

        public Criteria andHallNumGreaterThan(Integer value) {
            addCriterion("hall_num >", value, "hallNum");
            return (Criteria) this;
        }

        public Criteria andHallNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("hall_num >=", value, "hallNum");
            return (Criteria) this;
        }

        public Criteria andHallNumLessThan(Integer value) {
            addCriterion("hall_num <", value, "hallNum");
            return (Criteria) this;
        }

        public Criteria andHallNumLessThanOrEqualTo(Integer value) {
            addCriterion("hall_num <=", value, "hallNum");
            return (Criteria) this;
        }

        public Criteria andHallNumIn(List<Integer> values) {
            addCriterion("hall_num in", values, "hallNum");
            return (Criteria) this;
        }

        public Criteria andHallNumNotIn(List<Integer> values) {
            addCriterion("hall_num not in", values, "hallNum");
            return (Criteria) this;
        }

        public Criteria andHallNumBetween(Integer value1, Integer value2) {
            addCriterion("hall_num between", value1, value2, "hallNum");
            return (Criteria) this;
        }

        public Criteria andHallNumNotBetween(Integer value1, Integer value2) {
            addCriterion("hall_num not between", value1, value2, "hallNum");
            return (Criteria) this;
        }

        public Criteria andBathroomNumIsNull() {
            addCriterion("bathroom_num is null");
            return (Criteria) this;
        }

        public Criteria andBathroomNumIsNotNull() {
            addCriterion("bathroom_num is not null");
            return (Criteria) this;
        }

        public Criteria andBathroomNumEqualTo(Integer value) {
            addCriterion("bathroom_num =", value, "bathroomNum");
            return (Criteria) this;
        }

        public Criteria andBathroomNumNotEqualTo(Integer value) {
            addCriterion("bathroom_num <>", value, "bathroomNum");
            return (Criteria) this;
        }

        public Criteria andBathroomNumGreaterThan(Integer value) {
            addCriterion("bathroom_num >", value, "bathroomNum");
            return (Criteria) this;
        }

        public Criteria andBathroomNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("bathroom_num >=", value, "bathroomNum");
            return (Criteria) this;
        }

        public Criteria andBathroomNumLessThan(Integer value) {
            addCriterion("bathroom_num <", value, "bathroomNum");
            return (Criteria) this;
        }

        public Criteria andBathroomNumLessThanOrEqualTo(Integer value) {
            addCriterion("bathroom_num <=", value, "bathroomNum");
            return (Criteria) this;
        }

        public Criteria andBathroomNumIn(List<Integer> values) {
            addCriterion("bathroom_num in", values, "bathroomNum");
            return (Criteria) this;
        }

        public Criteria andBathroomNumNotIn(List<Integer> values) {
            addCriterion("bathroom_num not in", values, "bathroomNum");
            return (Criteria) this;
        }

        public Criteria andBathroomNumBetween(Integer value1, Integer value2) {
            addCriterion("bathroom_num between", value1, value2, "bathroomNum");
            return (Criteria) this;
        }

        public Criteria andBathroomNumNotBetween(Integer value1, Integer value2) {
            addCriterion("bathroom_num not between", value1, value2, "bathroomNum");
            return (Criteria) this;
        }

        public Criteria andKitchenNumIsNull() {
            addCriterion("kitchen_num is null");
            return (Criteria) this;
        }

        public Criteria andKitchenNumIsNotNull() {
            addCriterion("kitchen_num is not null");
            return (Criteria) this;
        }

        public Criteria andKitchenNumEqualTo(Integer value) {
            addCriterion("kitchen_num =", value, "kitchenNum");
            return (Criteria) this;
        }

        public Criteria andKitchenNumNotEqualTo(Integer value) {
            addCriterion("kitchen_num <>", value, "kitchenNum");
            return (Criteria) this;
        }

        public Criteria andKitchenNumGreaterThan(Integer value) {
            addCriterion("kitchen_num >", value, "kitchenNum");
            return (Criteria) this;
        }

        public Criteria andKitchenNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("kitchen_num >=", value, "kitchenNum");
            return (Criteria) this;
        }

        public Criteria andKitchenNumLessThan(Integer value) {
            addCriterion("kitchen_num <", value, "kitchenNum");
            return (Criteria) this;
        }

        public Criteria andKitchenNumLessThanOrEqualTo(Integer value) {
            addCriterion("kitchen_num <=", value, "kitchenNum");
            return (Criteria) this;
        }

        public Criteria andKitchenNumIn(List<Integer> values) {
            addCriterion("kitchen_num in", values, "kitchenNum");
            return (Criteria) this;
        }

        public Criteria andKitchenNumNotIn(List<Integer> values) {
            addCriterion("kitchen_num not in", values, "kitchenNum");
            return (Criteria) this;
        }

        public Criteria andKitchenNumBetween(Integer value1, Integer value2) {
            addCriterion("kitchen_num between", value1, value2, "kitchenNum");
            return (Criteria) this;
        }

        public Criteria andKitchenNumNotBetween(Integer value1, Integer value2) {
            addCriterion("kitchen_num not between", value1, value2, "kitchenNum");
            return (Criteria) this;
        }

        public Criteria andIntroductionIsNull() {
            addCriterion("introduction is null");
            return (Criteria) this;
        }

        public Criteria andIntroductionIsNotNull() {
            addCriterion("introduction is not null");
            return (Criteria) this;
        }

        public Criteria andIntroductionEqualTo(String value) {
            addCriterion("introduction =", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionNotEqualTo(String value) {
            addCriterion("introduction <>", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionGreaterThan(String value) {
            addCriterion("introduction >", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionGreaterThanOrEqualTo(String value) {
            addCriterion("introduction >=", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionLessThan(String value) {
            addCriterion("introduction <", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionLessThanOrEqualTo(String value) {
            addCriterion("introduction <=", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionLike(String value) {
            addCriterion("introduction like", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionNotLike(String value) {
            addCriterion("introduction not like", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionIn(List<String> values) {
            addCriterion("introduction in", values, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionNotIn(List<String> values) {
            addCriterion("introduction not in", values, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionBetween(String value1, String value2) {
            addCriterion("introduction between", value1, value2, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionNotBetween(String value1, String value2) {
            addCriterion("introduction not between", value1, value2, "introduction");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andIsVaildIsNull() {
            addCriterion("is_vaild is null");
            return (Criteria) this;
        }

        public Criteria andIsVaildIsNotNull() {
            addCriterion("is_vaild is not null");
            return (Criteria) this;
        }

        public Criteria andIsVaildEqualTo(Boolean value) {
            addCriterion("is_vaild =", value, "isVaild");
            return (Criteria) this;
        }

        public Criteria andIsVaildNotEqualTo(Boolean value) {
            addCriterion("is_vaild <>", value, "isVaild");
            return (Criteria) this;
        }

        public Criteria andIsVaildGreaterThan(Boolean value) {
            addCriterion("is_vaild >", value, "isVaild");
            return (Criteria) this;
        }

        public Criteria andIsVaildGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_vaild >=", value, "isVaild");
            return (Criteria) this;
        }

        public Criteria andIsVaildLessThan(Boolean value) {
            addCriterion("is_vaild <", value, "isVaild");
            return (Criteria) this;
        }

        public Criteria andIsVaildLessThanOrEqualTo(Boolean value) {
            addCriterion("is_vaild <=", value, "isVaild");
            return (Criteria) this;
        }

        public Criteria andIsVaildIn(List<Boolean> values) {
            addCriterion("is_vaild in", values, "isVaild");
            return (Criteria) this;
        }

        public Criteria andIsVaildNotIn(List<Boolean> values) {
            addCriterion("is_vaild not in", values, "isVaild");
            return (Criteria) this;
        }

        public Criteria andIsVaildBetween(Boolean value1, Boolean value2) {
            addCriterion("is_vaild between", value1, value2, "isVaild");
            return (Criteria) this;
        }

        public Criteria andIsVaildNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_vaild not between", value1, value2, "isVaild");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table house_type
     *
     * @mbggenerated do_not_delete_during_merge Fri Sep 15 09:37:31 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table house_type
     *
     * @mbggenerated Fri Sep 15 09:37:31 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}