package edu.ynu.software.Rocket.excellentHouse.entity;

import java.util.Date;

public class Post {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.id
     *
     * @mbggenerated Thu Sep 07 08:40:58 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.user_id
     *
     * @mbggenerated Thu Sep 07 08:40:58 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.entity_id
     *
     * @mbggenerated Thu Sep 07 08:40:58 CST 2017
     */
    private Integer entityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.entity_type
     *
     * @mbggenerated Thu Sep 07 08:40:58 CST 2017
     */
    private Integer entityType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.contains
     *
     * @mbggenerated Thu Sep 07 08:40:58 CST 2017
     */
    private String contains;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.create_time
     *
     * @mbggenerated Thu Sep 07 08:40:58 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.is_vaild
     *
     * @mbggenerated Thu Sep 07 08:40:58 CST 2017
     */
    private Boolean isVaild;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbggenerated Thu Sep 07 08:40:58 CST 2017
     */
    public Post(Integer id, Integer userId, Integer entityId, Integer entityType, String contains, Date createTime, Boolean isVaild) {
        this.id = id;
        this.userId = userId;
        this.entityId = entityId;
        this.entityType = entityType;
        this.contains = contains;
        this.createTime = createTime;
        this.isVaild = isVaild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbggenerated Thu Sep 07 08:40:58 CST 2017
     */
    public Post() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.id
     *
     * @return the value of post.id
     *
     * @mbggenerated Thu Sep 07 08:40:58 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.id
     *
     * @param id the value for post.id
     *
     * @mbggenerated Thu Sep 07 08:40:58 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.user_id
     *
     * @return the value of post.user_id
     *
     * @mbggenerated Thu Sep 07 08:40:58 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.user_id
     *
     * @param userId the value for post.user_id
     *
     * @mbggenerated Thu Sep 07 08:40:58 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.entity_id
     *
     * @return the value of post.entity_id
     *
     * @mbggenerated Thu Sep 07 08:40:58 CST 2017
     */
    public Integer getEntityId() {
        return entityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.entity_id
     *
     * @param entityId the value for post.entity_id
     *
     * @mbggenerated Thu Sep 07 08:40:58 CST 2017
     */
    public void setEntityId(Integer entityId) {
        this.entityId = entityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.entity_type
     *
     * @return the value of post.entity_type
     *
     * @mbggenerated Thu Sep 07 08:40:58 CST 2017
     */
    public Integer getEntityType() {
        return entityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.entity_type
     *
     * @param entityType the value for post.entity_type
     *
     * @mbggenerated Thu Sep 07 08:40:58 CST 2017
     */
    public void setEntityType(Integer entityType) {
        this.entityType = entityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.contains
     *
     * @return the value of post.contains
     *
     * @mbggenerated Thu Sep 07 08:40:58 CST 2017
     */
    public String getContains() {
        return contains;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.contains
     *
     * @param contains the value for post.contains
     *
     * @mbggenerated Thu Sep 07 08:40:58 CST 2017
     */
    public void setContains(String contains) {
        this.contains = contains == null ? null : contains.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.create_time
     *
     * @return the value of post.create_time
     *
     * @mbggenerated Thu Sep 07 08:40:58 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.create_time
     *
     * @param createTime the value for post.create_time
     *
     * @mbggenerated Thu Sep 07 08:40:58 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.is_vaild
     *
     * @return the value of post.is_vaild
     *
     * @mbggenerated Thu Sep 07 08:40:58 CST 2017
     */
    public Boolean getIsVaild() {
        return isVaild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.is_vaild
     *
     * @param isVaild the value for post.is_vaild
     *
     * @mbggenerated Thu Sep 07 08:40:58 CST 2017
     */
    public void setIsVaild(Boolean isVaild) {
        this.isVaild = isVaild;
    }
}