package edu.ynu.software.Rocket.excellentHouse.entity;

import java.util.Date;

public class SchoolNearby {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_nearby.id
     *
     * @mbggenerated Thu Sep 07 08:41:21 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_nearby.school_id
     *
     * @mbggenerated Thu Sep 07 08:41:21 CST 2017
     */
    private Integer schoolId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_nearby.premises_id
     *
     * @mbggenerated Thu Sep 07 08:41:21 CST 2017
     */
    private Integer premisesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_nearby.create_time
     *
     * @mbggenerated Thu Sep 07 08:41:21 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_nearby.is_vaild
     *
     * @mbggenerated Thu Sep 07 08:41:21 CST 2017
     */
    private Boolean isVaild;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_nearby
     *
     * @mbggenerated Thu Sep 07 08:41:21 CST 2017
     */
    public SchoolNearby(Integer id, Integer schoolId, Integer premisesId, Date createTime, Boolean isVaild) {
        this.id = id;
        this.schoolId = schoolId;
        this.premisesId = premisesId;
        this.createTime = createTime;
        this.isVaild = isVaild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_nearby
     *
     * @mbggenerated Thu Sep 07 08:41:21 CST 2017
     */
    public SchoolNearby() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_nearby.id
     *
     * @return the value of school_nearby.id
     *
     * @mbggenerated Thu Sep 07 08:41:21 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_nearby.id
     *
     * @param id the value for school_nearby.id
     *
     * @mbggenerated Thu Sep 07 08:41:21 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_nearby.school_id
     *
     * @return the value of school_nearby.school_id
     *
     * @mbggenerated Thu Sep 07 08:41:21 CST 2017
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_nearby.school_id
     *
     * @param schoolId the value for school_nearby.school_id
     *
     * @mbggenerated Thu Sep 07 08:41:21 CST 2017
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_nearby.premises_id
     *
     * @return the value of school_nearby.premises_id
     *
     * @mbggenerated Thu Sep 07 08:41:21 CST 2017
     */
    public Integer getPremisesId() {
        return premisesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_nearby.premises_id
     *
     * @param premisesId the value for school_nearby.premises_id
     *
     * @mbggenerated Thu Sep 07 08:41:21 CST 2017
     */
    public void setPremisesId(Integer premisesId) {
        this.premisesId = premisesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_nearby.create_time
     *
     * @return the value of school_nearby.create_time
     *
     * @mbggenerated Thu Sep 07 08:41:21 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_nearby.create_time
     *
     * @param createTime the value for school_nearby.create_time
     *
     * @mbggenerated Thu Sep 07 08:41:21 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_nearby.is_vaild
     *
     * @return the value of school_nearby.is_vaild
     *
     * @mbggenerated Thu Sep 07 08:41:21 CST 2017
     */
    public Boolean getIsVaild() {
        return isVaild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_nearby.is_vaild
     *
     * @param isVaild the value for school_nearby.is_vaild
     *
     * @mbggenerated Thu Sep 07 08:41:21 CST 2017
     */
    public void setIsVaild(Boolean isVaild) {
        this.isVaild = isVaild;
    }
}