package edu.ynu.software.Rocket.excellentHouse.entity;

import java.util.Date;

public class Transport {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transport.id
     *
     * @mbggenerated Thu Sep 07 08:41:27 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transport.name
     *
     * @mbggenerated Thu Sep 07 08:41:27 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transport.type
     *
     * @mbggenerated Thu Sep 07 08:41:27 CST 2017
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transport.address
     *
     * @mbggenerated Thu Sep 07 08:41:27 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transport.info
     *
     * @mbggenerated Thu Sep 07 08:41:27 CST 2017
     */
    private String info;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transport.create_time
     *
     * @mbggenerated Thu Sep 07 08:41:27 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transport.is_vaild
     *
     * @mbggenerated Thu Sep 07 08:41:27 CST 2017
     */
    private Boolean isVaild;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport
     *
     * @mbggenerated Thu Sep 07 08:41:27 CST 2017
     */
    public Transport(Integer id, String name, String type, String address, String info, Date createTime, Boolean isVaild) {
        this.id = id;
        this.name = name;
        this.type = type;
        this.address = address;
        this.info = info;
        this.createTime = createTime;
        this.isVaild = isVaild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport
     *
     * @mbggenerated Thu Sep 07 08:41:27 CST 2017
     */
    public Transport() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transport.id
     *
     * @return the value of transport.id
     *
     * @mbggenerated Thu Sep 07 08:41:27 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transport.id
     *
     * @param id the value for transport.id
     *
     * @mbggenerated Thu Sep 07 08:41:27 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transport.name
     *
     * @return the value of transport.name
     *
     * @mbggenerated Thu Sep 07 08:41:27 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transport.name
     *
     * @param name the value for transport.name
     *
     * @mbggenerated Thu Sep 07 08:41:27 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transport.type
     *
     * @return the value of transport.type
     *
     * @mbggenerated Thu Sep 07 08:41:27 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transport.type
     *
     * @param type the value for transport.type
     *
     * @mbggenerated Thu Sep 07 08:41:27 CST 2017
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transport.address
     *
     * @return the value of transport.address
     *
     * @mbggenerated Thu Sep 07 08:41:27 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transport.address
     *
     * @param address the value for transport.address
     *
     * @mbggenerated Thu Sep 07 08:41:27 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transport.info
     *
     * @return the value of transport.info
     *
     * @mbggenerated Thu Sep 07 08:41:27 CST 2017
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transport.info
     *
     * @param info the value for transport.info
     *
     * @mbggenerated Thu Sep 07 08:41:27 CST 2017
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transport.create_time
     *
     * @return the value of transport.create_time
     *
     * @mbggenerated Thu Sep 07 08:41:27 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transport.create_time
     *
     * @param createTime the value for transport.create_time
     *
     * @mbggenerated Thu Sep 07 08:41:27 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transport.is_vaild
     *
     * @return the value of transport.is_vaild
     *
     * @mbggenerated Thu Sep 07 08:41:27 CST 2017
     */
    public Boolean getIsVaild() {
        return isVaild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transport.is_vaild
     *
     * @param isVaild the value for transport.is_vaild
     *
     * @mbggenerated Thu Sep 07 08:41:27 CST 2017
     */
    public void setIsVaild(Boolean isVaild) {
        this.isVaild = isVaild;
    }
}