package edu.ynu.software.Rocket.excellentHouse.dao;

import edu.ynu.software.Rocket.excellentHouse.entity.Addressbase;
import edu.ynu.software.Rocket.excellentHouse.entity.AddressbaseExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface AddressbaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table addressbase
     *
     * @mbggenerated Wed Sep 20 22:16:03 CST 2017
     */
    int countByExample(AddressbaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table addressbase
     *
     * @mbggenerated Wed Sep 20 22:16:03 CST 2017
     */
    int deleteByExample(AddressbaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table addressbase
     *
     * @mbggenerated Wed Sep 20 22:16:03 CST 2017
     */
    @Delete({
        "delete from addressbase",
        "where city_id = #{cityId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String cityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table addressbase
     *
     * @mbggenerated Wed Sep 20 22:16:03 CST 2017
     */
    @Insert({
        "insert into addressbase (city_id, city_name, ",
        "up_id, kind_id)",
        "values (#{cityId,jdbcType=VARCHAR}, #{cityName,jdbcType=VARCHAR}, ",
        "#{upId,jdbcType=VARCHAR}, #{kindId,jdbcType=VARCHAR})"
    })
    int insert(Addressbase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table addressbase
     *
     * @mbggenerated Wed Sep 20 22:16:03 CST 2017
     */
    int insertSelective(Addressbase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table addressbase
     *
     * @mbggenerated Wed Sep 20 22:16:03 CST 2017
     */
    List<Addressbase> selectByExample(AddressbaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table addressbase
     *
     * @mbggenerated Wed Sep 20 22:16:03 CST 2017
     */
    @Select({
        "select",
        "city_id, city_name, up_id, kind_id",
        "from addressbase",
        "where city_id = #{cityId,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    Addressbase selectByPrimaryKey(String cityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table addressbase
     *
     * @mbggenerated Wed Sep 20 22:16:03 CST 2017
     */
    int updateByExampleSelective(@Param("record") Addressbase record, @Param("example") AddressbaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table addressbase
     *
     * @mbggenerated Wed Sep 20 22:16:03 CST 2017
     */
    int updateByExample(@Param("record") Addressbase record, @Param("example") AddressbaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table addressbase
     *
     * @mbggenerated Wed Sep 20 22:16:03 CST 2017
     */
    int updateByPrimaryKeySelective(Addressbase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table addressbase
     *
     * @mbggenerated Wed Sep 20 22:16:03 CST 2017
     */
    @Update({
        "update addressbase",
        "set city_name = #{cityName,jdbcType=VARCHAR},",
          "up_id = #{upId,jdbcType=VARCHAR},",
          "kind_id = #{kindId,jdbcType=VARCHAR}",
        "where city_id = #{cityId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Addressbase record);
}