package edu.ynu.software.Rocket.excellentHouse.dao;

import edu.ynu.software.Rocket.excellentHouse.entity.CollectionDecoCompany;
import edu.ynu.software.Rocket.excellentHouse.entity.CollectionDecoCompanyExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface CollectionDecoCompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_deco_company
     *
     * @mbggenerated Thu Sep 07 08:39:44 CST 2017
     */
    int countByExample(CollectionDecoCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_deco_company
     *
     * @mbggenerated Thu Sep 07 08:39:44 CST 2017
     */
    int deleteByExample(CollectionDecoCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_deco_company
     *
     * @mbggenerated Thu Sep 07 08:39:44 CST 2017
     */
    @Delete({
        "delete from collection_deco_company",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_deco_company
     *
     * @mbggenerated Thu Sep 07 08:39:44 CST 2017
     */
    @Insert({
        "insert into collection_deco_company (id, deco_company_id, ",
        "user_id, create_time, ",
        "is_vaild)",
        "values (#{id,jdbcType=INTEGER}, #{decoCompanyId,jdbcType=INTEGER}, ",
        "#{userId,jdbcType=INTEGER}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{isVaild,jdbcType=BIT})"
    })
    int insert(CollectionDecoCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_deco_company
     *
     * @mbggenerated Thu Sep 07 08:39:44 CST 2017
     */
    int insertSelective(CollectionDecoCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_deco_company
     *
     * @mbggenerated Thu Sep 07 08:39:44 CST 2017
     */
    List<CollectionDecoCompany> selectByExample(CollectionDecoCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_deco_company
     *
     * @mbggenerated Thu Sep 07 08:39:44 CST 2017
     */
    @Select({
        "select",
        "id, deco_company_id, user_id, create_time, is_vaild",
        "from collection_deco_company",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    CollectionDecoCompany selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_deco_company
     *
     * @mbggenerated Thu Sep 07 08:39:44 CST 2017
     */
    int updateByExampleSelective(@Param("record") CollectionDecoCompany record, @Param("example") CollectionDecoCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_deco_company
     *
     * @mbggenerated Thu Sep 07 08:39:44 CST 2017
     */
    int updateByExample(@Param("record") CollectionDecoCompany record, @Param("example") CollectionDecoCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_deco_company
     *
     * @mbggenerated Thu Sep 07 08:39:44 CST 2017
     */
    int updateByPrimaryKeySelective(CollectionDecoCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_deco_company
     *
     * @mbggenerated Thu Sep 07 08:39:44 CST 2017
     */
    @Update({
        "update collection_deco_company",
        "set deco_company_id = #{decoCompanyId,jdbcType=INTEGER},",
          "user_id = #{userId,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "is_vaild = #{isVaild,jdbcType=BIT}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(CollectionDecoCompany record);
}