package edu.ynu.software.Rocket.excellentHouse.dao;

import edu.ynu.software.Rocket.excellentHouse.entity.CollectionDesigner;
import edu.ynu.software.Rocket.excellentHouse.entity.CollectionDesignerExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface CollectionDesignerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_designer
     *
     * @mbggenerated Thu Sep 07 08:40:02 CST 2017
     */
    int countByExample(CollectionDesignerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_designer
     *
     * @mbggenerated Thu Sep 07 08:40:02 CST 2017
     */
    int deleteByExample(CollectionDesignerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_designer
     *
     * @mbggenerated Thu Sep 07 08:40:02 CST 2017
     */
    @Delete({
        "delete from collection_designer",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_designer
     *
     * @mbggenerated Thu Sep 07 08:40:02 CST 2017
     */
    @Insert({
        "insert into collection_designer (id, designer_id, ",
        "user_id, create_time, ",
        "is_vaild)",
        "values (#{id,jdbcType=INTEGER}, #{designerId,jdbcType=INTEGER}, ",
        "#{userId,jdbcType=INTEGER}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{isVaild,jdbcType=BIT})"
    })
    int insert(CollectionDesigner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_designer
     *
     * @mbggenerated Thu Sep 07 08:40:02 CST 2017
     */
    int insertSelective(CollectionDesigner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_designer
     *
     * @mbggenerated Thu Sep 07 08:40:02 CST 2017
     */
    List<CollectionDesigner> selectByExample(CollectionDesignerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_designer
     *
     * @mbggenerated Thu Sep 07 08:40:02 CST 2017
     */
    @Select({
        "select",
        "id, designer_id, user_id, create_time, is_vaild",
        "from collection_designer",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    CollectionDesigner selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_designer
     *
     * @mbggenerated Thu Sep 07 08:40:02 CST 2017
     */
    int updateByExampleSelective(@Param("record") CollectionDesigner record, @Param("example") CollectionDesignerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_designer
     *
     * @mbggenerated Thu Sep 07 08:40:02 CST 2017
     */
    int updateByExample(@Param("record") CollectionDesigner record, @Param("example") CollectionDesignerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_designer
     *
     * @mbggenerated Thu Sep 07 08:40:02 CST 2017
     */
    int updateByPrimaryKeySelective(CollectionDesigner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_designer
     *
     * @mbggenerated Thu Sep 07 08:40:02 CST 2017
     */
    @Update({
        "update collection_designer",
        "set designer_id = #{designerId,jdbcType=INTEGER},",
          "user_id = #{userId,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "is_vaild = #{isVaild,jdbcType=BIT}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(CollectionDesigner record);
}