package edu.ynu.software.Rocket.excellentHouse.dao;

import edu.ynu.software.Rocket.excellentHouse.entity.CollectionHouse;
import edu.ynu.software.Rocket.excellentHouse.entity.CollectionHouseExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface CollectionHouseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_house
     *
     * @mbggenerated Thu Sep 07 08:40:07 CST 2017
     */
    int countByExample(CollectionHouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_house
     *
     * @mbggenerated Thu Sep 07 08:40:07 CST 2017
     */
    int deleteByExample(CollectionHouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_house
     *
     * @mbggenerated Thu Sep 07 08:40:07 CST 2017
     */
    @Delete({
        "delete from collection_house",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_house
     *
     * @mbggenerated Thu Sep 07 08:40:07 CST 2017
     */
    @Insert({
        "insert into collection_house (id, house_id, ",
        "user_id, create_time, ",
        "is_vaild)",
        "values (#{id,jdbcType=INTEGER}, #{houseId,jdbcType=INTEGER}, ",
        "#{userId,jdbcType=INTEGER}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{isVaild,jdbcType=BIT})"
    })
    int insert(CollectionHouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_house
     *
     * @mbggenerated Thu Sep 07 08:40:07 CST 2017
     */
    int insertSelective(CollectionHouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_house
     *
     * @mbggenerated Thu Sep 07 08:40:07 CST 2017
     */
    List<CollectionHouse> selectByExample(CollectionHouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_house
     *
     * @mbggenerated Thu Sep 07 08:40:07 CST 2017
     */
    @Select({
        "select",
        "id, house_id, user_id, create_time, is_vaild",
        "from collection_house",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    CollectionHouse selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_house
     *
     * @mbggenerated Thu Sep 07 08:40:07 CST 2017
     */
    int updateByExampleSelective(@Param("record") CollectionHouse record, @Param("example") CollectionHouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_house
     *
     * @mbggenerated Thu Sep 07 08:40:07 CST 2017
     */
    int updateByExample(@Param("record") CollectionHouse record, @Param("example") CollectionHouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_house
     *
     * @mbggenerated Thu Sep 07 08:40:07 CST 2017
     */
    int updateByPrimaryKeySelective(CollectionHouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_house
     *
     * @mbggenerated Thu Sep 07 08:40:07 CST 2017
     */
    @Update({
        "update collection_house",
        "set house_id = #{houseId,jdbcType=INTEGER},",
          "user_id = #{userId,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "is_vaild = #{isVaild,jdbcType=BIT}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(CollectionHouse record);
}