package edu.ynu.software.Rocket.excellentHouse.dao;

import edu.ynu.software.Rocket.excellentHouse.entity.CollectionPremises;
import edu.ynu.software.Rocket.excellentHouse.entity.CollectionPremisesExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface CollectionPremisesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_premises
     *
     * @mbggenerated Thu Sep 07 08:40:13 CST 2017
     */
    int countByExample(CollectionPremisesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_premises
     *
     * @mbggenerated Thu Sep 07 08:40:13 CST 2017
     */
    int deleteByExample(CollectionPremisesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_premises
     *
     * @mbggenerated Thu Sep 07 08:40:13 CST 2017
     */
    @Delete({
        "delete from collection_premises",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_premises
     *
     * @mbggenerated Thu Sep 07 08:40:13 CST 2017
     */
    @Insert({
        "insert into collection_premises (id, premisesId, ",
        "userId, create_time, ",
        "is_vaild)",
        "values (#{id,jdbcType=INTEGER}, #{premisesid,jdbcType=INTEGER}, ",
        "#{userid,jdbcType=INTEGER}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{isVaild,jdbcType=BIT})"
    })
    int insert(CollectionPremises record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_premises
     *
     * @mbggenerated Thu Sep 07 08:40:13 CST 2017
     */
    int insertSelective(CollectionPremises record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_premises
     *
     * @mbggenerated Thu Sep 07 08:40:13 CST 2017
     */
    List<CollectionPremises> selectByExample(CollectionPremisesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_premises
     *
     * @mbggenerated Thu Sep 07 08:40:13 CST 2017
     */
    @Select({
        "select",
        "id, premisesId, userId, create_time, is_vaild",
        "from collection_premises",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    CollectionPremises selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_premises
     *
     * @mbggenerated Thu Sep 07 08:40:13 CST 2017
     */
    int updateByExampleSelective(@Param("record") CollectionPremises record, @Param("example") CollectionPremisesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_premises
     *
     * @mbggenerated Thu Sep 07 08:40:13 CST 2017
     */
    int updateByExample(@Param("record") CollectionPremises record, @Param("example") CollectionPremisesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_premises
     *
     * @mbggenerated Thu Sep 07 08:40:13 CST 2017
     */
    int updateByPrimaryKeySelective(CollectionPremises record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_premises
     *
     * @mbggenerated Thu Sep 07 08:40:13 CST 2017
     */
    @Update({
        "update collection_premises",
        "set premisesId = #{premisesid,jdbcType=INTEGER},",
          "userId = #{userid,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "is_vaild = #{isVaild,jdbcType=BIT}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(CollectionPremises record);
}