package edu.ynu.software.Rocket.excellentHouse.dao;

import edu.ynu.software.Rocket.excellentHouse.entity.DecoInstance;
import edu.ynu.software.Rocket.excellentHouse.entity.DecoInstanceExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface DecoInstanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deco_instance
     *
     * @mbggenerated Wed Sep 20 21:20:07 CST 2017
     */
    int countByExample(DecoInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deco_instance
     *
     * @mbggenerated Wed Sep 20 21:20:07 CST 2017
     */
    int deleteByExample(DecoInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deco_instance
     *
     * @mbggenerated Wed Sep 20 21:20:07 CST 2017
     */
    @Delete({
        "delete from deco_instance",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deco_instance
     *
     * @mbggenerated Wed Sep 20 21:20:07 CST 2017
     */
    @Insert({
        "insert into deco_instance (id, premises_id, ",
        "designer_id, name, ",
        "budget, introduction, ",
        "type, style, create_time, ",
        "is_vaild)",
        "values (#{id,jdbcType=INTEGER}, #{premisesId,jdbcType=INTEGER}, ",
        "#{designerId,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{budget,jdbcType=DECIMAL}, #{introduction,jdbcType=VARCHAR}, ",
        "#{type,jdbcType=VARCHAR}, #{style,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{isVaild,jdbcType=BIT})"
    })
    int insert(DecoInstance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deco_instance
     *
     * @mbggenerated Wed Sep 20 21:20:07 CST 2017
     */
    int insertSelective(DecoInstance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deco_instance
     *
     * @mbggenerated Wed Sep 20 21:20:07 CST 2017
     */
    List<DecoInstance> selectByExample(DecoInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deco_instance
     *
     * @mbggenerated Wed Sep 20 21:20:07 CST 2017
     */
    @Select({
        "select",
        "id, premises_id, designer_id, name, budget, introduction, type, style, create_time, ",
        "is_vaild",
        "from deco_instance",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    DecoInstance selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deco_instance
     *
     * @mbggenerated Wed Sep 20 21:20:07 CST 2017
     */
    int updateByExampleSelective(@Param("record") DecoInstance record, @Param("example") DecoInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deco_instance
     *
     * @mbggenerated Wed Sep 20 21:20:07 CST 2017
     */
    int updateByExample(@Param("record") DecoInstance record, @Param("example") DecoInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deco_instance
     *
     * @mbggenerated Wed Sep 20 21:20:07 CST 2017
     */
    int updateByPrimaryKeySelective(DecoInstance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deco_instance
     *
     * @mbggenerated Wed Sep 20 21:20:07 CST 2017
     */
    @Update({
        "update deco_instance",
        "set premises_id = #{premisesId,jdbcType=INTEGER},",
          "designer_id = #{designerId,jdbcType=INTEGER},",
          "name = #{name,jdbcType=VARCHAR},",
          "budget = #{budget,jdbcType=DECIMAL},",
          "introduction = #{introduction,jdbcType=VARCHAR},",
          "type = #{type,jdbcType=VARCHAR},",
          "style = #{style,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "is_vaild = #{isVaild,jdbcType=BIT}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(DecoInstance record);
}