package edu.ynu.software.Rocket.excellentHouse.dao;

import edu.ynu.software.Rocket.excellentHouse.entity.Designer;
import edu.ynu.software.Rocket.excellentHouse.entity.DesignerExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface DesignerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table designer
     *
     * @mbggenerated Thu Sep 07 08:40:39 CST 2017
     */
    int countByExample(DesignerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table designer
     *
     * @mbggenerated Thu Sep 07 08:40:39 CST 2017
     */
    int deleteByExample(DesignerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table designer
     *
     * @mbggenerated Thu Sep 07 08:40:39 CST 2017
     */
    @Delete({
        "delete from designer",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table designer
     *
     * @mbggenerated Thu Sep 07 08:40:39 CST 2017
     */
    @Insert({
        "insert into designer (id, deco_company_id, ",
        "name, well_in_style, ",
        "phone, create_time, ",
        "is_vaild)",
        "values (#{id,jdbcType=INTEGER}, #{decoCompanyId,jdbcType=INTEGER}, ",
        "#{name,jdbcType=VARCHAR}, #{wellInStyle,jdbcType=VARCHAR}, ",
        "#{phone,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{isVaild,jdbcType=BIT})"
    })
    int insert(Designer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table designer
     *
     * @mbggenerated Thu Sep 07 08:40:39 CST 2017
     */
    int insertSelective(Designer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table designer
     *
     * @mbggenerated Thu Sep 07 08:40:39 CST 2017
     */
    List<Designer> selectByExample(DesignerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table designer
     *
     * @mbggenerated Thu Sep 07 08:40:39 CST 2017
     */
    @Select({
        "select",
        "id, deco_company_id, name, well_in_style, phone, create_time, is_vaild",
        "from designer",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    Designer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table designer
     *
     * @mbggenerated Thu Sep 07 08:40:39 CST 2017
     */
    int updateByExampleSelective(@Param("record") Designer record, @Param("example") DesignerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table designer
     *
     * @mbggenerated Thu Sep 07 08:40:39 CST 2017
     */
    int updateByExample(@Param("record") Designer record, @Param("example") DesignerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table designer
     *
     * @mbggenerated Thu Sep 07 08:40:39 CST 2017
     */
    int updateByPrimaryKeySelective(Designer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table designer
     *
     * @mbggenerated Thu Sep 07 08:40:39 CST 2017
     */
    @Update({
        "update designer",
        "set deco_company_id = #{decoCompanyId,jdbcType=INTEGER},",
          "name = #{name,jdbcType=VARCHAR},",
          "well_in_style = #{wellInStyle,jdbcType=VARCHAR},",
          "phone = #{phone,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "is_vaild = #{isVaild,jdbcType=BIT}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Designer record);
}