package edu.ynu.software.Rocket.excellentHouse.dao;

import edu.ynu.software.Rocket.excellentHouse.entity.HouseType;
import edu.ynu.software.Rocket.excellentHouse.entity.HouseTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface HouseTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_type
     *
     * @mbggenerated Thu Sep 07 08:40:49 CST 2017
     */
    int countByExample(HouseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_type
     *
     * @mbggenerated Thu Sep 07 08:40:49 CST 2017
     */
    int deleteByExample(HouseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_type
     *
     * @mbggenerated Thu Sep 07 08:40:49 CST 2017
     */
    @Delete({
        "delete from house_type",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_type
     *
     * @mbggenerated Thu Sep 07 08:40:49 CST 2017
     */
    @Insert({
        "insert into house_type (id, premises_id, ",
        "name, area, avePrice, ",
        "totalPrice, bedroomNum, ",
        "hallNum, bathroomNum, ",
        "kitchenNum, introduction, ",
        "create_time, is_vaild)",
        "values (#{id,jdbcType=INTEGER}, #{premisesId,jdbcType=INTEGER}, ",
        "#{name,jdbcType=VARCHAR}, #{area,jdbcType=INTEGER}, #{aveprice,jdbcType=DECIMAL}, ",
        "#{totalprice,jdbcType=DECIMAL}, #{bedroomnum,jdbcType=INTEGER}, ",
        "#{hallnum,jdbcType=INTEGER}, #{bathroomnum,jdbcType=INTEGER}, ",
        "#{kitchennum,jdbcType=INTEGER}, #{introduction,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{isVaild,jdbcType=BIT})"
    })
    int insert(HouseType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_type
     *
     * @mbggenerated Thu Sep 07 08:40:49 CST 2017
     */
    int insertSelective(HouseType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_type
     *
     * @mbggenerated Thu Sep 07 08:40:49 CST 2017
     */
    List<HouseType> selectByExample(HouseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_type
     *
     * @mbggenerated Thu Sep 07 08:40:49 CST 2017
     */
    @Select({
        "select",
        "id, premises_id, name, area, avePrice, totalPrice, bedroomNum, hallNum, bathroomNum, ",
        "kitchenNum, introduction, create_time, is_vaild",
        "from house_type",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    HouseType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_type
     *
     * @mbggenerated Thu Sep 07 08:40:49 CST 2017
     */
    int updateByExampleSelective(@Param("record") HouseType record, @Param("example") HouseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_type
     *
     * @mbggenerated Thu Sep 07 08:40:49 CST 2017
     */
    int updateByExample(@Param("record") HouseType record, @Param("example") HouseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_type
     *
     * @mbggenerated Thu Sep 07 08:40:49 CST 2017
     */
    int updateByPrimaryKeySelective(HouseType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_type
     *
     * @mbggenerated Thu Sep 07 08:40:49 CST 2017
     */
    @Update({
        "update house_type",
        "set premises_id = #{premisesId,jdbcType=INTEGER},",
          "name = #{name,jdbcType=VARCHAR},",
          "area = #{area,jdbcType=INTEGER},",
          "avePrice = #{aveprice,jdbcType=DECIMAL},",
          "totalPrice = #{totalprice,jdbcType=DECIMAL},",
          "bedroomNum = #{bedroomnum,jdbcType=INTEGER},",
          "hallNum = #{hallnum,jdbcType=INTEGER},",
          "bathroomNum = #{bathroomnum,jdbcType=INTEGER},",
          "kitchenNum = #{kitchennum,jdbcType=INTEGER},",
          "introduction = #{introduction,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "is_vaild = #{isVaild,jdbcType=BIT}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(HouseType record);
}