package edu.ynu.software.Rocket.excellentHouse.dao;

import edu.ynu.software.Rocket.excellentHouse.entity.House;
import edu.ynu.software.Rocket.excellentHouse.entity.HouseExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface HouseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbggenerated Mon Sep 25 20:11:08 CST 2017
     */
    int countByExample(HouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbggenerated Mon Sep 25 20:11:08 CST 2017
     */
    int deleteByExample(HouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbggenerated Mon Sep 25 20:11:08 CST 2017
     */
    @Delete({
        "delete from house",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbggenerated Mon Sep 25 20:11:08 CST 2017
     */
    @Insert({
        "insert into house (premises_id, type_id, ",
        "user_id, kind, name, ",
        "area, decoration, floor, ",
        "introduction, house_price, ",
        "create_time, is_vaild, ",
        "city_id, location_x, ",
        "location_y, contact_name, ",
        "contact_phone, type)",
        "values (#{premisesId,jdbcType=INTEGER}, #{typeId,jdbcType=INTEGER}, ",
        "#{userId,jdbcType=INTEGER}, #{kind,jdbcType=VARCHAR}, #{name,jdbcType=VARCHAR}, ",
        "#{area,jdbcType=REAL}, #{decoration,jdbcType=VARCHAR}, #{floor,jdbcType=INTEGER}, ",
        "#{introduction,jdbcType=VARCHAR}, #{housePrice,jdbcType=DECIMAL}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{isVaild,jdbcType=BIT}, ",
        "#{cityId,jdbcType=INTEGER}, #{locationX,jdbcType=REAL}, ",
        "#{locationY,jdbcType=REAL}, #{contactName,jdbcType=VARCHAR}, ",
        "#{contactPhone,jdbcType=VARCHAR}, #{type,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(House record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbggenerated Mon Sep 25 20:11:08 CST 2017
     */
    int insertSelective(House record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbggenerated Mon Sep 25 20:11:08 CST 2017
     */
    List<House> selectByExample(HouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbggenerated Mon Sep 25 20:11:08 CST 2017
     */
    @Select({
        "select",
        "id, premises_id, type_id, user_id, kind, name, area, decoration, floor, introduction, ",
        "house_price, create_time, is_vaild, city_id, location_x, location_y, contact_name, ",
        "contact_phone, type",
        "from house",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    House selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbggenerated Mon Sep 25 20:11:08 CST 2017
     */
    int updateByExampleSelective(@Param("record") House record, @Param("example") HouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbggenerated Mon Sep 25 20:11:08 CST 2017
     */
    int updateByExample(@Param("record") House record, @Param("example") HouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbggenerated Mon Sep 25 20:11:08 CST 2017
     */
    int updateByPrimaryKeySelective(House record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbggenerated Mon Sep 25 20:11:08 CST 2017
     */
    @Update({
        "update house",
        "set premises_id = #{premisesId,jdbcType=INTEGER},",
          "type_id = #{typeId,jdbcType=INTEGER},",
          "user_id = #{userId,jdbcType=INTEGER},",
          "kind = #{kind,jdbcType=VARCHAR},",
          "name = #{name,jdbcType=VARCHAR},",
          "area = #{area,jdbcType=REAL},",
          "decoration = #{decoration,jdbcType=VARCHAR},",
          "floor = #{floor,jdbcType=INTEGER},",
          "introduction = #{introduction,jdbcType=VARCHAR},",
          "house_price = #{housePrice,jdbcType=DECIMAL},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "is_vaild = #{isVaild,jdbcType=BIT},",
          "city_id = #{cityId,jdbcType=INTEGER},",
          "location_x = #{locationX,jdbcType=REAL},",
          "location_y = #{locationY,jdbcType=REAL},",
          "contact_name = #{contactName,jdbcType=VARCHAR},",
          "contact_phone = #{contactPhone,jdbcType=VARCHAR},",
          "type = #{type,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(House record);
}