package edu.ynu.software.Rocket.excellentHouse.dao;

import edu.ynu.software.Rocket.excellentHouse.entity.Post;
import edu.ynu.software.Rocket.excellentHouse.entity.PostExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface PostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbggenerated Thu Sep 07 08:40:58 CST 2017
     */
    int countByExample(PostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbggenerated Thu Sep 07 08:40:58 CST 2017
     */
    int deleteByExample(PostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbggenerated Thu Sep 07 08:40:58 CST 2017
     */
    @Delete({
        "delete from post",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbggenerated Thu Sep 07 08:40:58 CST 2017
     */
    @Insert({
        "insert into post (id, user_id, ",
        "entity_id, entity_type, ",
        "contains, create_time, ",
        "is_vaild)",
        "values (#{id,jdbcType=INTEGER}, #{userId,jdbcType=INTEGER}, ",
        "#{entityId,jdbcType=INTEGER}, #{entityType,jdbcType=INTEGER}, ",
        "#{contains,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{isVaild,jdbcType=BIT})"
    })
    int insert(Post record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbggenerated Thu Sep 07 08:40:58 CST 2017
     */
    int insertSelective(Post record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbggenerated Thu Sep 07 08:40:58 CST 2017
     */
    List<Post> selectByExample(PostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbggenerated Thu Sep 07 08:40:58 CST 2017
     */
    @Select({
        "select",
        "id, user_id, entity_id, entity_type, contains, create_time, is_vaild",
        "from post",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    Post selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbggenerated Thu Sep 07 08:40:58 CST 2017
     */
    int updateByExampleSelective(@Param("record") Post record, @Param("example") PostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbggenerated Thu Sep 07 08:40:58 CST 2017
     */
    int updateByExample(@Param("record") Post record, @Param("example") PostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbggenerated Thu Sep 07 08:40:58 CST 2017
     */
    int updateByPrimaryKeySelective(Post record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbggenerated Thu Sep 07 08:40:58 CST 2017
     */
    @Update({
        "update post",
        "set user_id = #{userId,jdbcType=INTEGER},",
          "entity_id = #{entityId,jdbcType=INTEGER},",
          "entity_type = #{entityType,jdbcType=INTEGER},",
          "contains = #{contains,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "is_vaild = #{isVaild,jdbcType=BIT}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Post record);
}