package edu.ynu.software.Rocket.excellentHouse.dao;

import edu.ynu.software.Rocket.excellentHouse.entity.Premises;
import edu.ynu.software.Rocket.excellentHouse.entity.PremisesExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface PremisesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table premises
     *
     * @mbggenerated Mon Sep 11 11:09:38 CST 2017
     */
    int countByExample(PremisesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table premises
     *
     * @mbggenerated Mon Sep 11 11:09:38 CST 2017
     */
    int deleteByExample(PremisesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table premises
     *
     * @mbggenerated Mon Sep 11 11:09:38 CST 2017
     */
    @Delete({
        "delete from premises",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table premises
     *
     * @mbggenerated Mon Sep 11 11:09:38 CST 2017
     */
    @Insert({
        "insert into premises (id, company_id, ",
        "name, location, address, ",
        "average_price, phone, ",
        "opening_time, create_time, ",
        "is_valid, state, serviceable_year, ",
        "sale_address, deliver_time, ",
        "licence_number, licence_time, ",
        "licence_info, area, ",
        "parking_number, greening_rate, ",
        "introction, type)",
        "values (#{id,jdbcType=INTEGER}, #{companyId,jdbcType=INTEGER}, ",
        "#{name,jdbcType=VARCHAR}, #{location,jdbcType=OTHER}, #{address,jdbcType=VARCHAR}, ",
        "#{averagePrice,jdbcType=DECIMAL}, #{phone,jdbcType=VARCHAR}, ",
        "#{openingTime,jdbcType=DATE}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{isValid,jdbcType=BIT}, #{state,jdbcType=INTEGER}, #{serviceableYear,jdbcType=INTEGER}, ",
        "#{saleAddress,jdbcType=VARCHAR}, #{deliverTime,jdbcType=DATE}, ",
        "#{licenceNumber,jdbcType=VARCHAR}, #{licenceTime,jdbcType=DATE}, ",
        "#{licenceInfo,jdbcType=VARCHAR}, #{area,jdbcType=INTEGER}, ",
        "#{parkingNumber,jdbcType=INTEGER}, #{greeningRate,jdbcType=REAL}, ",
        "#{introction,jdbcType=VARCHAR}, #{type,jdbcType=VARCHAR})"
    })
    int insert(Premises record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table premises
     *
     * @mbggenerated Mon Sep 11 11:09:38 CST 2017
     */
    int insertSelective(Premises record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table premises
     *
     * @mbggenerated Mon Sep 11 11:09:38 CST 2017
     */
    List<Premises> selectByExample(PremisesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table premises
     *
     * @mbggenerated Mon Sep 11 11:09:38 CST 2017
     */
    @Select({
        "select",
        "id, company_id, name, location, address, average_price, phone, opening_time, ",
        "create_time, is_valid, state, serviceable_year, sale_address, deliver_time, ",
        "licence_number, licence_time, licence_info, area, parking_number, greening_rate, ",
        "introction, type",
        "from premises",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    Premises selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table premises
     *
     * @mbggenerated Mon Sep 11 11:09:38 CST 2017
     */
    int updateByExampleSelective(@Param("record") Premises record, @Param("example") PremisesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table premises
     *
     * @mbggenerated Mon Sep 11 11:09:38 CST 2017
     */
    int updateByExample(@Param("record") Premises record, @Param("example") PremisesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table premises
     *
     * @mbggenerated Mon Sep 11 11:09:38 CST 2017
     */
    int updateByPrimaryKeySelective(Premises record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table premises
     *
     * @mbggenerated Mon Sep 11 11:09:38 CST 2017
     */
    @Update({
        "update premises",
        "set company_id = #{companyId,jdbcType=INTEGER},",
          "name = #{name,jdbcType=VARCHAR},",
          "location = #{location,jdbcType=OTHER},",
          "address = #{address,jdbcType=VARCHAR},",
          "average_price = #{averagePrice,jdbcType=DECIMAL},",
          "phone = #{phone,jdbcType=VARCHAR},",
          "opening_time = #{openingTime,jdbcType=DATE},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "is_valid = #{isValid,jdbcType=BIT},",
          "state = #{state,jdbcType=INTEGER},",
          "serviceable_year = #{serviceableYear,jdbcType=INTEGER},",
          "sale_address = #{saleAddress,jdbcType=VARCHAR},",
          "deliver_time = #{deliverTime,jdbcType=DATE},",
          "licence_number = #{licenceNumber,jdbcType=VARCHAR},",
          "licence_time = #{licenceTime,jdbcType=DATE},",
          "licence_info = #{licenceInfo,jdbcType=VARCHAR},",
          "area = #{area,jdbcType=INTEGER},",
          "parking_number = #{parkingNumber,jdbcType=INTEGER},",
          "greening_rate = #{greeningRate,jdbcType=REAL},",
          "introction = #{introction,jdbcType=VARCHAR},",
          "type = #{type,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Premises record);
}