package edu.ynu.software.Rocket.excellentHouse.dao;

import edu.ynu.software.Rocket.excellentHouse.entity.SchoolNearby;
import edu.ynu.software.Rocket.excellentHouse.entity.SchoolNearbyExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface SchoolNearbyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_nearby
     *
     * @mbggenerated Thu Sep 07 08:41:21 CST 2017
     */
    int countByExample(SchoolNearbyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_nearby
     *
     * @mbggenerated Thu Sep 07 08:41:21 CST 2017
     */
    int deleteByExample(SchoolNearbyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_nearby
     *
     * @mbggenerated Thu Sep 07 08:41:21 CST 2017
     */
    @Delete({
        "delete from school_nearby",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_nearby
     *
     * @mbggenerated Thu Sep 07 08:41:21 CST 2017
     */
    @Insert({
        "insert into school_nearby (id, school_id, ",
        "premises_id, create_time, ",
        "is_vaild)",
        "values (#{id,jdbcType=INTEGER}, #{schoolId,jdbcType=INTEGER}, ",
        "#{premisesId,jdbcType=INTEGER}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{isVaild,jdbcType=BIT})"
    })
    int insert(SchoolNearby record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_nearby
     *
     * @mbggenerated Thu Sep 07 08:41:21 CST 2017
     */
    int insertSelective(SchoolNearby record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_nearby
     *
     * @mbggenerated Thu Sep 07 08:41:21 CST 2017
     */
    List<SchoolNearby> selectByExample(SchoolNearbyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_nearby
     *
     * @mbggenerated Thu Sep 07 08:41:21 CST 2017
     */
    @Select({
        "select",
        "id, school_id, premises_id, create_time, is_vaild",
        "from school_nearby",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    SchoolNearby selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_nearby
     *
     * @mbggenerated Thu Sep 07 08:41:21 CST 2017
     */
    int updateByExampleSelective(@Param("record") SchoolNearby record, @Param("example") SchoolNearbyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_nearby
     *
     * @mbggenerated Thu Sep 07 08:41:21 CST 2017
     */
    int updateByExample(@Param("record") SchoolNearby record, @Param("example") SchoolNearbyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_nearby
     *
     * @mbggenerated Thu Sep 07 08:41:21 CST 2017
     */
    int updateByPrimaryKeySelective(SchoolNearby record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_nearby
     *
     * @mbggenerated Thu Sep 07 08:41:21 CST 2017
     */
    @Update({
        "update school_nearby",
        "set school_id = #{schoolId,jdbcType=INTEGER},",
          "premises_id = #{premisesId,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "is_vaild = #{isVaild,jdbcType=BIT}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(SchoolNearby record);
}