package edu.ynu.software.Rocket.excellentHouse.dao;

import edu.ynu.software.Rocket.excellentHouse.entity.Transport;
import edu.ynu.software.Rocket.excellentHouse.entity.TransportExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface TransportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport
     *
     * @mbggenerated Thu Sep 07 08:41:27 CST 2017
     */
    int countByExample(TransportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport
     *
     * @mbggenerated Thu Sep 07 08:41:27 CST 2017
     */
    int deleteByExample(TransportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport
     *
     * @mbggenerated Thu Sep 07 08:41:27 CST 2017
     */
    @Delete({
        "delete from transport",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport
     *
     * @mbggenerated Thu Sep 07 08:41:27 CST 2017
     */
    @Insert({
        "insert into transport (id, name, ",
        "type, address, info, ",
        "create_time, is_vaild)",
        "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{type,jdbcType=VARCHAR}, #{address,jdbcType=VARCHAR}, #{info,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{isVaild,jdbcType=BIT})"
    })
    int insert(Transport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport
     *
     * @mbggenerated Thu Sep 07 08:41:27 CST 2017
     */
    int insertSelective(Transport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport
     *
     * @mbggenerated Thu Sep 07 08:41:27 CST 2017
     */
    List<Transport> selectByExample(TransportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport
     *
     * @mbggenerated Thu Sep 07 08:41:27 CST 2017
     */
    @Select({
        "select",
        "id, name, type, address, info, create_time, is_vaild",
        "from transport",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    Transport selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport
     *
     * @mbggenerated Thu Sep 07 08:41:27 CST 2017
     */
    int updateByExampleSelective(@Param("record") Transport record, @Param("example") TransportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport
     *
     * @mbggenerated Thu Sep 07 08:41:27 CST 2017
     */
    int updateByExample(@Param("record") Transport record, @Param("example") TransportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport
     *
     * @mbggenerated Thu Sep 07 08:41:27 CST 2017
     */
    int updateByPrimaryKeySelective(Transport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport
     *
     * @mbggenerated Thu Sep 07 08:41:27 CST 2017
     */
    @Update({
        "update transport",
        "set name = #{name,jdbcType=VARCHAR},",
          "type = #{type,jdbcType=VARCHAR},",
          "address = #{address,jdbcType=VARCHAR},",
          "info = #{info,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "is_vaild = #{isVaild,jdbcType=BIT}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Transport record);
}