package edu.ynu.software.Rocket.excellentHouse.dao;

import edu.ynu.software.Rocket.excellentHouse.entity.TransportNearby;
import edu.ynu.software.Rocket.excellentHouse.entity.TransportNearbyExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface TransportNearbyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport_nearby
     *
     * @mbggenerated Thu Sep 07 08:41:33 CST 2017
     */
    int countByExample(TransportNearbyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport_nearby
     *
     * @mbggenerated Thu Sep 07 08:41:33 CST 2017
     */
    int deleteByExample(TransportNearbyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport_nearby
     *
     * @mbggenerated Thu Sep 07 08:41:33 CST 2017
     */
    @Delete({
        "delete from transport_nearby",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport_nearby
     *
     * @mbggenerated Thu Sep 07 08:41:33 CST 2017
     */
    @Insert({
        "insert into transport_nearby (id, transport_id, ",
        "premises_id, create_id, ",
        "is_vaild)",
        "values (#{id,jdbcType=INTEGER}, #{transportId,jdbcType=INTEGER}, ",
        "#{premisesId,jdbcType=INTEGER}, #{createId,jdbcType=TIMESTAMP}, ",
        "#{isVaild,jdbcType=BIT})"
    })
    int insert(TransportNearby record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport_nearby
     *
     * @mbggenerated Thu Sep 07 08:41:33 CST 2017
     */
    int insertSelective(TransportNearby record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport_nearby
     *
     * @mbggenerated Thu Sep 07 08:41:33 CST 2017
     */
    List<TransportNearby> selectByExample(TransportNearbyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport_nearby
     *
     * @mbggenerated Thu Sep 07 08:41:33 CST 2017
     */
    @Select({
        "select",
        "id, transport_id, premises_id, create_id, is_vaild",
        "from transport_nearby",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    TransportNearby selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport_nearby
     *
     * @mbggenerated Thu Sep 07 08:41:33 CST 2017
     */
    int updateByExampleSelective(@Param("record") TransportNearby record, @Param("example") TransportNearbyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport_nearby
     *
     * @mbggenerated Thu Sep 07 08:41:33 CST 2017
     */
    int updateByExample(@Param("record") TransportNearby record, @Param("example") TransportNearbyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport_nearby
     *
     * @mbggenerated Thu Sep 07 08:41:33 CST 2017
     */
    int updateByPrimaryKeySelective(TransportNearby record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport_nearby
     *
     * @mbggenerated Thu Sep 07 08:41:33 CST 2017
     */
    @Update({
        "update transport_nearby",
        "set transport_id = #{transportId,jdbcType=INTEGER},",
          "premises_id = #{premisesId,jdbcType=INTEGER},",
          "create_id = #{createId,jdbcType=TIMESTAMP},",
          "is_vaild = #{isVaild,jdbcType=BIT}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TransportNearby record);
}