package edu.ynu.software.Rocket.excellentHouse.dao;

import edu.ynu.software.Rocket.excellentHouse.entity.User;
import org.apache.ibatis.annotations.Insert;

/**
 * Created by August on 2017/9/11.
 */
public interface UserCustomizedMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Thu Sep 07 08:41:38 CST 2017
     */
    @Insert({
            "insert into user (user_id, email, ",
            "pass_word, gender, name, ",
            "phone_number, state, ",
            "create_time, is_vaild)",
            "values (#{userId,jdbcType=INTEGER}, #{email,jdbcType=VARCHAR}, ",
            "#{passWord,jdbcType=VARCHAR}, #{gender,jdbcType=BIT}, #{name,jdbcType=VARCHAR}, ",
            "#{phoneNumber,jdbcType=VARCHAR}, #{state,jdbcType=VARCHAR}, ",
            "#{createTime,jdbcType=TIMESTAMP}, #{isVaild,jdbcType=BIT})"
    })
    int insert(User record);
}
